import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {PortfolioAlerts} from '../src/portfolio-alerts.js';import {ROADMAP_FEED,validateRoadmap,roadmapText} from '../src/roadmap-alerts.js';import worker,{telegramWebhookSecret} from '../src/index.js';
const digest=d=>{d.editorial_hash=createHash('sha256').update(JSON.stringify({revision:d.revision,reviewed_at:d.reviewed_at,review_due:d.review_due,routes:d.routes,companies:d.companies,views:d.views})).digest('hex');return d;};
const fixture=()=>digest({schema_version:1,revision:'2026-10-03.1',reviewed_at:'2026-10-03',review_due:'2026-11-03',routes:['compute','power','agents','trust','worlds'].map(id=>({id,name:{zh:'测试路线'},thesis:{zh:'研究假设'},confirm:{zh:'核对现金流'},invalidate:{zh:'现金流恶化'},tickers:['NVDA'],claims:['view']})),companies:[{ticker:'NVDA'}],views:[{id:'view'}],discovery:{candidates:[{id:'old',title:'Old AI video',published_at:'2026-10-01T00:00:00Z',route_ids:['agents'],status:'metadata_only'}]}});
function harness(t){const state=new Map(),sent=[];let d=fixture(),okay=true,feed=true,clock=Date.parse('2026-10-04T00:00:00Z');const ctx={storage:{get:async k=>structuredClone(state.get(k)),put:async(k,v)=>state.set(k,structuredClone(v))}},env={TELEGRAM_BOT_TOKEN:'test-token',TELEGRAM_CHAT_ID:'test-owner'},obj=new PortfolioAlerts(ctx,env);t.mock.method(Date,'now',()=>clock);t.mock.method(globalThis,'fetch',async(url,init)=>{if(url===ROADMAP_FEED)return feed?Response.json(d):new Response('no',{status:503});assert.equal(url,'https://api.telegram.org/bottest-token/sendMessage');const body=JSON.parse(init.body);assert.equal(body.chat_id,'test-owner');assert.ok(body.text.length<4096);sent.push(body.text);return Response.json(okay?{ok:true,result:{message_id:sent.length}}:{ok:false});});return {state,sent,obj,set:x=>d=x,fail:()=>okay=false,fix:()=>okay=true,feedFail:()=>feed=false,advance:(ms=61000)=>clock+=ms,run:async(a='run')=>(await obj.fetch(new Request('https://internal/roadmap/'+a))).json()};}
test('first acknowledgement, concurrent deduplication and unchanged check',async t=>{const h=harness(t);const runs=await Promise.all([h.run(),h.run()]);assert.equal(runs.reduce((s,r)=>s+r.sent,0),1);h.advance();assert.equal((await h.run()).reason,'unchanged');const status=await h.run('public');assert.ok(status.last_ack_at);assert.ok(!JSON.stringify(status).includes('message_id'));assert.equal(h.sent.length,1);});
test('failed send retains baseline and retries',async t=>{const h=harness(t);h.fail();assert.equal((await h.run()).sent,0);assert.equal(h.state.get('roadmap-state-v1').sent_hash,undefined);h.fix();h.advance();assert.equal((await h.run()).sent,1);});
test('revision change sends, rollback and unversioned changes fail closed',async t=>{const h=harness(t);await h.run();const d=fixture();d.revision='2026-10-03.2';d.routes[0].confirm.zh='新证据';digest(d);h.set(d);h.advance();assert.equal((await h.run()).sent,1);assert.match(h.sent[1],/路线修订/);await assert.rejects(()=>validateRoadmap(fixture(),d));const bad=structuredClone(d);bad.routes[0].confirm.zh='silent edit';digest(bad);await assert.rejects(()=>validateRoadmap(bad,d));});
test('new video metadata is a review lead, historical backfills stay silent',async t=>{const h=harness(t);await h.run();const d=fixture();d.discovery.candidates.push({id:'backfill',title:'Old unseen agent',published_at:'2026-10-02T00:00:00Z',route_ids:['agents'],status:'metadata_only'});h.set(d);h.advance();assert.equal((await h.run()).sent,0);d.discovery.candidates.push({id:'fresh',title:'New agent video',published_at:'2026-10-04T01:00:00Z',route_ids:['agents'],status:'metadata_only'});h.advance(3600000);assert.equal((await h.run()).sent,1);assert.match(h.sent[1],/未形成投资结论/);});
test('pause, explicit read and source failure do not send',async t=>{const h=harness(t);await h.run('pause');assert.equal((await h.run()).reason,'paused');assert.ok((await h.run('read')).text);assert.equal(h.sent.length,0);await h.run('resume');h.feedFail();assert.equal((await h.run()).reason,'source_unavailable');assert.equal(h.sent.length,0);assert.equal((await h.run('bogus')).error,'unknown_action');});
test('future metadata rejected and no trade promises',async()=>{const d=fixture();d.discovery.candidates.push({...d.discovery.candidates[0],id:'future',published_at:'2099-01-01'});await assert.rejects(()=>validateRoadmap(d));assert.match(roadmapText(fixture()),/不自动下单/);});
test('invalid calendar dates and silent review extensions are rejected',async()=>{for(const date of ['2026-99-99','2027-02-30']){const d=fixture();d.review_due=date;digest(d);await assert.rejects(()=>validateRoadmap(d),/invalid_date/);}const previous=fixture(),d=fixture();d.review_due='2026-12-03';await assert.rejects(()=>validateRoadmap(d,previous),/digest_mismatch/);digest(d);await assert.rejects(()=>validateRoadmap(d,previous),/rollback_or_unversioned_change/);});
test('owner commands reject spoofed webhook, other chat and groups',async()=>{const secret=await telegramWebhookSecret({}, {token:'test-token'});let calls=0;const env={TELEGRAM_BOT_TOKEN:'test-token',TELEGRAM_CHAT_ID:'123',PORTFOLIO_ALERTS:{idFromName:()=>'',get:()=>({fetch:async()=>{calls++;return Response.json({ok:true,enabled:true,text:'query'});}})}};for(const [chat,header]of [[{id:123,type:'private'},'bad'],[{id:456,type:'private'},secret],[{id:123,type:'group'},secret]]){const r=await worker.fetch(new Request('https://invest.agiscorecard.com/tg-webhook',{method:'POST',headers:{'content-type':'application/json','x-telegram-bot-api-secret-token':header},body:JSON.stringify({message:{chat,text:'/roadmap'}})}),env,{waitUntil(){}});assert.equal(r.status,403);}const r=await worker.fetch(new Request('https://invest.agiscorecard.com/api/roadmap-alerts?action=run',{method:'POST'}),env,{waitUntil(){}});assert.equal(r.status,403);assert.equal(calls,0);});
