// 孙宇晨预判档案:预判 → 验证结果 → 他同期的操作
// 来源见仓库 report/ 目录调研报告;⚠ 表示该条未完成三票核验
export const PREDICTIONS = [
  {
    date: "2019-05-07",
    channel: "X (Twitter)",
    prediction: "TRX 将在 2019 年 6 月重回市值前十(当时约第 11 名)",
    outcome: "落空:6 月底 TRX 仍列第 11",
    verdict: "miss",
    action: "同期在推特高频造势拉盘,BTT 于 Binance Launchpad 上线后持续营销",
    note: "⚠ 单源(CCN),未完成三票核验",
  },
  {
    date: "2019-05-07",
    channel: "X (Twitter)",
    prediction: "BTT 将在 2019 年 Q2 进入市值前 30(当时约第 50)",
    outcome: "部分命中:曾短暂触及第 30,6 月底回落至第 36;被友好媒体渲染为『兑现承诺』",
    verdict: "partial",
    action: "借排名叙事持续推广 BTT 生态",
    note: "⚠ 未完成三票核验",
  },
  {
    date: "2019-06",
    channel: "eBay 慈善拍卖 / 微博 / X",
    prediction: "宣称要用巴菲特午餐『转化』比特币怀疑论者(非预判,营销事件)",
    outcome: "营销造势:以约 457 万美元拍下午餐,后一度以健康理由推迟,引发信任危机",
    verdict: "marketing",
    action: "全渠道公关轰炸;TRX 随事件剧烈波动",
    note: "⚠ 定性依据多源报道",
  },
  {
    date: "2021-01",
    channel: "Benzinga / HackerNoon 访谈",
    prediction: "拒绝给出 BTC 价格目标,称市场『走向均衡,必有拉升与回撤』;1 月回调是健康的,牛市延续;山寨季将至",
    outcome: "方向命中(4 月 6.4 万→7 月 2.9 万→11 月 6.9 万;上半年山寨普涨),但措辞模糊近乎不可证伪,且为当时共识",
    verdict: "hit-weak",
    action: "同一访谈中夹带推广 TRON 为『DeFi 热土』(实际 TVL 远落后于 ETH/BSC)",
    note: "均衡论已 3-0 核验;山寨季条目 ⚠",
  },
  {
    date: "2023-09-05",
    channel: "Korea Blockchain Week 演讲",
    prediction: "市场处于新牛市周期转折点,两年内进入新牛市(理由:3AC/FTX 去杠杆近尾声)",
    outcome: "命中:2024 年 BTC ETF+减半行情、2024 年 11 月大选后暴涨,窗口内兑现。档案中含金量最高的一次",
    verdict: "hit",
    action: "彼时已被 SEC 起诉(2023-03),继续扩张 HTX 与波场稳定币版图",
    note: "⚠ 核验中断(信源为 Cryptonews + 转载)",
  },
  {
    date: "2024-11 → 2025-05",
    channel: "资本动作(非言论)",
    prediction: "隐含预判:特朗普当选将逆转加密监管环境,押注政治关系可解 SEC 之困",
    outcome: "命中:SEC 案 2025-02 中止、2026-03 和解(Rainberry 付 1000 万美元,对孙个人指控撤销);国会质疑利益交换",
    verdict: "hit",
    action: "WLFI 投资 7500 万美元(最大公开投资者)+ 购入约 1 亿美元 $TRUMP;以最大持有者身份赴总统晚宴",
    note: "投资额经国会信函 3-0 核验;和解细节 ⚠",
  },
  {
    date: "2025-06-16",
    channel: "SEC 8-K / 纳斯达克",
    prediction: "隐含预判:Circle IPO 成功 = 『稳定币/加密股夏天』,美股愿为 TRX 财库付溢价",
    outcome: "短期兑现:SRM 公告日暴涨约 460-530%(⚠);7-17 更名 Tron Inc.(NASDAQ: TRON),7-24 敲钟",
    verdict: "hit",
    action: "借壳 SRM:1 亿美元 TRX 财库协议($0.50 转股价优先股+权证,最高 2.1 亿美元);7-28 提交 10 亿美元 shelf;孙任『顾问』规避高管责任",
    note: "交易结构经 SEC 文件 3-0 核验",
  },
  {
    date: "2025-09 → 2026-05",
    channel: "法院文书 / X",
    prediction: "(风险事件,非预判)与特朗普家族 WLFI 决裂",
    outcome: "WLFI 冻结其约 2.4 亿美元代币 → 2026-04 孙起诉 WLFI 欺诈 → 2026-05-04 WLFI 反诉诽谤及市场操纵(水军 400 万粉丝、稻草人购币、疑似做空)",
    verdict: "risk",
    action: "公开称反诉为『毫无价值的公关噱头』;政治庇护叙事反转为政治对抗",
    note: "⚠ 多源一致,未完成三票核验",
  },
  {
    date: "2025-11-06",
    channel: "X (Twitter)",
    prediction: "『短期缺芯片,长期缺能源,永远缺存储』——芯片与能源短缺是周期性的,存储短缺是永久性的",
    outcome: "命中(幅度罕见):此后一年内闪迪 SanDisk(SNDK)从约 35 美元最高涨至 1439 美元(约 50 倍,并纳入纳斯达克100);三星/海力士/美光 HBM 产能被预订至 2027-28 年",
    verdict: "hit",
    action: "同期将存储列入 TRON AI 基金重点赛道;借『50倍存储』战绩在中文互联网强化『预言家』人设(注意幸存者叙事风险)",
    note: "⚠ 原话时间(2025-11-06)与 SNDK 涨幅经中文财经媒体多源转述,未见英文一手推文存档,采信前建议核对其 X 原帖",
  },
  {
    date: "2026-05-16",
    channel: "X / 演讲(多家媒体 2026-05-17~22 转述)",
    prediction: "『虚拟 AI 普及红利已彻底结束,未来三年核心机会只在物理 AI』——具身智能(人形机器人)、无人机、空间计算、太空探索四大核心赛道",
    outcome: "待验证(预测窗口 2026-2029):可跟踪人形机器人出货量(Unitree 2025 年出货约 5500 台居全球第一)、特斯拉 Optimus 量产进度等硬指标",
    verdict: "pending",
    action: "TRON AI 基金从 1 亿美元扩至 10 亿美元,覆盖八大赛道(具身智能/无人机/空间计算/机器人/工业自动化/能源/存储/光通信);此前个人花 2.8 亿美元完成太空飞行为『太空经济』站台",
    note: "⚠ 中文媒体多源一致但均为转述;基金扩容数字待 TRON DAO 官方公告核验",
  },
  {
    date: "2026-03",
    channel: "X / BeInCrypto 报道",
    prediction: "Tron Inc. 是『更便宜、更赚钱的中国版 Circle』:TRON 链年利润约 33 亿美元,市值仅 Circle 的 1/70",
    outcome: "逻辑硬伤:33 亿是网络层利润,不归上市壳公司;Tron Inc. 只是 TRX 财库,不捕获协议费",
    verdict: "marketing",
    action: "Tron Inc. 以每日约 5 万美元定投 TRX(财库达约 6.86 亿枚),边宣传边加仓自家币",
    note: "⚠ 单源",
  },
];

// 跨市场标的映射(美股/港股/A股)。
// 注意:除 TRON 外均为"预判主题→标的"的映射,不代表孙宇晨实际持仓;A股无直接加密标的。
export const STOCKS = [
  // ---- 美股 ----
  { market: "美股", ticker: "TRON", name: "Tron Inc.", relation: 5, theme: "直接载体", logic: "TRX 价格 × 财库数量 → 每股 NAV;孙的言论/诉讼直接冲击股价", risk: "壳公司、10 亿美元 shelf 稀释、国会质询上市资格、WLFI 互诉外溢",
    fund: { mcap: "财库约 6.86 亿枚 TRX(按 TRX≈$0.33 约值 2.3 亿美元);公司市值随增发变动,待核", val: "无常规估值锚,交易的是 mNAV 溢价/折价", inv: "『存货』即 TRX 本身:币价跌 → 财库缩水 → 增发买币飞轮变负反馈", moat: "唯一 TRX 财库股(稀缺性=孙宇晨本人)", comp: "MSTR 及各类 DAT 币库股(板块已现 mNAV 折价)" } },
  { market: "美股", ticker: "SNDK", name: "SanDisk", relation: 3, theme: "存储", logic: "『永远缺存储』论的标志性验证标的", risk: "华尔街已公开警示 H2 深度回调;其言论是叙事放大器而非基本面来源",
    fund: { mcap: "股价 2025 初 $37 → 2026-06 超 $2000,H1 +858% 为标普第一", val: "前瞻 PE 约 32(一年前仅 19,估值扩张远快于盈利);LTM 营收 132 亿美元 +83%", inv: "涨价周期低库存快周转,存货重估是利润弹性来源——周期反转时同一存货变减值", moat: "美股唯一纯 NAND 大盘标的(自 WDC 分拆),稀缺性溢价明显", comp: "三星/铠侠/美光 NAND;SKHY 上市后稀缺性被稀释、资金被分流" } },
  { market: "美股", ticker: "MU", name: "Micron", relation: 3, theme: "存储", logic: "HBM/DRAM 主线,产能预订至 2027-28 的直接受益者", risk: "毛利率 84.9% 历史峰值本身就是周期顶部特征",
    fund: { mcap: "FY26Q3 单季营收 415 亿美元(超预期 16%)、净利 282 亿(+12 倍)", val: "前瞻 PE 仅约 8——存储股 PE 最低的时候往往最接近盈利顶,低 PE 是周期陷阱不是安全边际", inv: "HBM 无库存压力(售罄至 2027-28);利基产品库存开始回升需跟踪", moat: "美国本土唯一 DRAM/HBM 大厂,地缘稀缺性", comp: "SKHY(HBM 份额约 60%,即将同台交易)、三星" } },
  { market: "美股", ticker: "WDC", name: "Western Digital", relation: 2, theme: "存储", logic: "HDD/近线存储,AI 数据中心冷数据层", risk: "弹性最小,防守型",
    fund: { mcap: "—", val: "板块内估值最低", inv: "HDD 交期拉长、提价温和", moat: "HDD 全球双寡头之一", comp: "希捷 STX(双寡头)、SSD 对 HDD 的长期替代" } },
  { market: "美股", ticker: "SKHY", name: "SK海力士 ADR", relation: 3, theme: "存储", logic: "HBM 份额约 60% 的全球龙头,拟 7/10 前后挂牌", risk: "天量新股+周期高位上市=派发信号,不宜打新式追高",
    fund: { mcap: "拟发行 1779 万股新股募资约 290 亿美元(超阿里巴巴 2014/沙特阿美 2019)", val: "韩股年内 +300% 后定价,估值锚在高位", inv: "已规划 5 年产能翻倍并接受设备商提价——供给反转的最硬证据,也是整个存储线的退潮倒计时", moat: "HBM 技术与份额全球第一", comp: "MU、三星;上市后与 MU 直接争夺美股资金" } },
  { market: "美股", ticker: "NVDA", name: "NVIDIA", relation: 2, theme: "物理AI", logic: "物理 AI 的算力+仿真底座(Isaac/Jetson Thor)", risk: "与孙的关联仅为主题呼应",
    fund: { mcap: "约 4.72 万亿美元,全球第一(2026-07)", val: "高估值但由真实盈利支撑(具体 PE 待核)", inv: "供不应求,无库存问题", moat: "机器人训练+仿真+边缘推理全栈生态近乎垄断,物理 AI 卖铲人", comp: "AMD、华为昇腾、地平线(边缘端)" } },
  { market: "美股", ticker: "TSLA", name: "Tesla", relation: 2, theme: "物理AI", logic: "Optimus:弗里蒙特产线 7 月底-8 月投产,初期目标年产能 100 万台", risk: "量产时间表历史上屡次跳票;媒体已质疑『承诺多于进展』",
    fund: { mcap: "约 180x trailing PE / 14x 营收——估值已透支 Robotaxi+Optimus 多年成功执行", val: "Model S/X 已于 5 月停产让线给 Optimus,属背水一战式转型", inv: "—", moat: "唯一垂直整合(芯片-整机-数据-工厂)的人形机器人玩家", comp: "Unitree(2025 出货 5500 台全球第一)、Figure、优必选" } },
  { market: "美股", ticker: "RKLB", name: "Rocket Lab", relation: 2, theme: "太空", logic: "『太空经济』赛道的可投美股代表", risk: "发射毛利低,商业化节奏不确定",
    fund: { mcap: "—", val: "PS 估值,亏损", inv: "—", moat: "SpaceX 之外唯一高频商业发射+空间系统标的", comp: "SpaceX(私有,碾压级)、Firefly" } },
  { market: "美股", ticker: "CEG", name: "Constellation Energy", relation: 2, theme: "能源", logic: "『长期缺能源』论的核电/AI 电力主线", risk: "电价与签约节奏",
    fund: { mcap: "—", val: "有真实合同与利润,估值可用 PE 锚定", inv: "—", moat: "美国最大核电机组组合,数据中心 PPA 先行者", comp: "VST、NRG、无收入的 SMR 概念(OKLO 类,回避)" } },
  { market: "美股", ticker: "CRCL", name: "Circle", relation: 2, theme: "稳定币", logic: "孙自比『中国版 Circle』反证其为稳定币主线正统标的", risk: "已较上市后高点大幅回落——加密线周期后段的直接证据",
    fund: { mcap: "约 160-170 亿美元(2026-07 初)", val: "PE 为负(约 -103),盈利依赖利率×USDC 规模", inv: "—", moat: "美股唯一纯稳定币发行商,GENIUS 法案合规红利", comp: "Tether(私有、规模数倍)、银行系稳定币、PayPal PYUSD" } },
  { market: "美股", ticker: "COIN", name: "Coinbase", relation: 2, theme: "加密Beta", logic: "『牛市周期』的交易所 Beta", risk: "市值仅约 436 亿美元($165.70,2026-07-04)——较峰值大幅回落,佐证周期后段",
    fund: { mcap: "约 436 亿美元", val: "盈利随币价周期大起大落", inv: "—", moat: "美股龙头合规交易所+USDC 分成", comp: "HOOD、Kraken、币安(离岸)" } },
  { market: "美股", ticker: "HOOD", name: "Robinhood", relation: 2, theme: "加密Beta", logic: "散户交易活跃度 Beta", risk: "同周期风险",
    fund: { mcap: "—", val: "—", inv: "—", moat: "散户入口+加密+股票一站式", comp: "COIN、嘉信、Webull" } },
  { market: "美股", ticker: "MSTR", name: "Strategy", relation: 2, theme: "币库股", logic: "币库股模式源头", risk: "板块 mNAV 折价已现",
    fund: { mcap: "—", val: "交易 BTC 财库溢价/折价", inv: "『存货』=BTC", moat: "最大 BTC 财库+可转债融资机器", comp: "各类 DAT 币库股(含 TRON)" } },
  { market: "美股", ticker: "DJT", name: "Trump Media", relation: 1, theme: "特朗普概念", logic: "孙与特朗普家族互诉的负面情绪源", risk: "纯情绪/政治盘",
    fund: { mcap: "—", val: "与基本面无关", inv: "—", moat: "—", comp: "—" } },
  // ---- 港股 ----
  { market: "港股", ticker: "9880.HK", name: "优必选", relation: 3, theme: "物理AI", logic: "人形机器人第一股;2026-07-01 宣布订单破万台并公布售价——0→1 验证的关键事件", risk: "亏损,PE 不适用;万台订单的收入确认节奏是真伪试金石",
    fund: { mcap: "约 422 亿港元(2026-04),订单破万后待重估", val: "PS 约 25 倍(行业以 PS 估值,普遍亏损)", inv: "2025 全尺寸出货 1079 台(+35867%)、收入 8.2 亿(+2204%),全球第一", moat: "全尺寸人形机器人量产交付经验全球最多", comp: "Unitree(出货 5500 台居首但以小尺寸为主)、特斯拉 Optimus、Figure" } },
  { market: "港股", ticker: "9660.HK", name: "地平线机器人", relation: 2, theme: "物理AI", logic: "智驾/机器人计算方案,物理 AI 芯片层", risk: "亏损;竞争激烈",
    fund: { mcap: "—", val: "PS 估值", inv: "—", moat: "国产智驾芯片出货量第一,征程系列生态", comp: "NVDA(Thor)、华为昇腾、黑芝麻" } },
  { market: "港股", ticker: "2498.HK", name: "速腾聚创", relation: 2, theme: "物理AI", logic: "激光雷达=物理 AI 感知层,已切入机器人客户", risk: "价格战毛利承压",
    fund: { mcap: "—", val: "PS 估值", inv: "—", moat: "车载激光雷达出货前二,机器人第二曲线", comp: "禾赛 HSAI(美股)、华为" } },
  { market: "港股", ticker: "1810.HK", name: "小米集团", relation: 1, theme: "物理AI", logic: "汽车+IoT+机器人生态泛映射", risk: "关联度弱", fund: { mcap: "—", val: "—", inv: "—", moat: "生态+制造", comp: "华为、苹果" } },
  { market: "港股", ticker: "0981.HK", name: "中芯国际", relation: 2, theme: "存储/芯片", logic: "『缺芯片』论的中国制造端映射", risk: "先进制程受限",
    fund: { mcap: "—", val: "A/H 溢价大", inv: "—", moat: "大陆代工龙头,国产替代唯一规模载体", comp: "台积电(技术代差)、华虹" } },
  { market: "港股", ticker: "1347.HK", name: "华虹半导体", relation: 1, theme: "存储/芯片", logic: "特色工艺代工 Beta", risk: "周期性强", fund: { mcap: "—", val: "—", inv: "—", moat: "特色工艺(功率/嵌入式存储)", comp: "中芯、世界先进" } },
  { market: "港股", ticker: "0863.HK", name: "OSL 集团", relation: 2, theme: "加密Beta", logic: "港股持牌加密交易所", risk: "流动性差波动大",
    fund: { mcap: "小盘", val: "—", inv: "—", moat: "香港持牌合规交易所稀缺牌照", comp: "HashKey、富途/老虎的加密通道" } },
  { market: "港股", ticker: "1816.HK", name: "中广核电力", relation: 1, theme: "能源", logic: "『长期缺能源』港股核电映射", risk: "电价管制弹性低", fund: { mcap: "—", val: "股息率定价(<3.5% 性价比消失)", inv: "—", moat: "在运核电规模", comp: "中国核电(A)" } },
  { market: "港股", ticker: "6651.HK", name: "五一视界", relation: 1, theme: "物理AI", logic: "数字孪生/空间计算映射", risk: "小盘题材", fund: { mcap: "小盘", val: "—", inv: "—", moat: "数字孪生场景积累", comp: "51WORLD 同赛道创业公司众多" } },
  // ---- A股 ----
  { market: "A股", ticker: "603986.SH", name: "兆易创新", relation: 3, theme: "存储", logic: "存储设计龙头,『永远缺存储』论 A 股核心映射", risk: "主业(NOR/利基DRAM)与 HBM 主线错位,估值含大量周期溢价",
    fund: { mcap: "约 5440 亿元(2026-06-25 创新高,半年市值增超 4000 亿)", val: "PE 百倍级(待核),涨价预期定价充分", inv: "设计公司库存轻,弹性来自涨价传导", moat: "NOR Flash 全球前二+利基 DRAM 国产替代", comp: "华邦、旺宏、北京君正" } },
  { market: "A股", ticker: "301308.SZ", name: "江波龙", relation: 3, theme: "存储", logic: "存储模组,NAND 涨价最直接受益", risk: "两个月 +200% 后追高风险大;模组壁垒低",
    fund: { mcap: "约 2865 亿元(2026-06-25)", val: "涨价周期 PE 失真,看存货重估", inv: "在手存货约 85 亿元——涨价时是利润放大器,周期反转时同一批存货变减值雷", moat: "国内模组龙头,嵌入式存储客户绑定", comp: "佰维存储、威刚、金士顿" } },
  { market: "A股", ticker: "688525.SH", name: "佰维存储", relation: 2, theme: "存储", logic: "模组+先进封测,同属涨价链", risk: "二线补涨属性=顶部信号载体",
    fund: { mcap: "约 2264 亿元(2026-06-25)", val: "同江波龙逻辑", inv: "存货重估弹性", moat: "自研封测一体化", comp: "江波龙、德明利" } },
  { market: "A股", ticker: "688008.SH", name: "澜起科技", relation: 2, theme: "存储", logic: "内存接口芯片,DDR5/服务器升级受益", risk: "估值高",
    fund: { mcap: "约 3412 亿元(2026-06-25)", val: "PE 高但商业模式优于模组", inv: "轻库存", moat: "内存接口芯片全球双寡头(与 Rambus)", comp: "Rambus" } },
  { market: "A股", ticker: "688017.SH", name: "绿的谐波", relation: 2, theme: "物理AI", logic: "谐波减速器=人形机器人核心件", risk: "单日 +17% 级别的过热波动;订单未放量前纯题材定价",
    fund: { mcap: "5/26 约 640 亿 → 6 月底股价 485.9 元(单日+17.6%),市值约 800-900 亿(待核)", val: "PE 百倍级题材溢价;券商预计 2026 机器人业务占比超 50%", inv: "—", moat: "谐波减速器全球市占约 15% 国产第一,已进特斯拉供应链", comp: "哈默纳科 HD(全球约 70%,真正的垄断者)、来福谐波" } },
  { market: "A股", ticker: "002050.SZ", name: "三花智控", relation: 2, theme: "物理AI", logic: "机器人机电执行器核心供应商+特斯拉链", risk: "机器人收入占比尚小",
    fund: { mcap: "—", val: "主业(热管理)PE 定价+机器人期权", inv: "—", moat: "全球制冷控制与汽车热管理双龙头,Optimus 执行器供应商", comp: "拓普集团(同为特斯拉链执行器)" } },
  { market: "A股", ticker: "002747.SZ", name: "埃斯顿", relation: 2, theme: "物理AI", logic: "工业机器人本体国产第一", risk: "盈利承压", fund: { mcap: "—", val: "—", inv: "—", moat: "本体+核心部件自制率高", comp: "发那科、汇川" } },
  { market: "A股", ticker: "300124.SZ", name: "汇川技术", relation: 2, theme: "物理AI", logic: "工控/伺服龙头,工业自动化基本盘", risk: "制造业周期", fund: { mcap: "—", val: "—", inv: "—", moat: "国产工控第一,伺服/PLC 全线", comp: "西门子、台达" } },
  { market: "A股", ticker: "601985.SH", name: "中国核电", relation: 1, theme: "能源", logic: "A 股核电映射", risk: "电价审批", fund: { mcap: "—", val: "股息率定价", inv: "—", moat: "在运+在建核电规模", comp: "中国广核" } },
  { market: "A股", ticker: "600118.SH", name: "中国卫星", relation: 1, theme: "太空", logic: "太空赛道 A 股映射", risk: "军工波动", fund: { mcap: "—", val: "—", inv: "—", moat: "卫星制造总装稀缺牌照", comp: "航天电子" } },
  { market: "A股", ticker: "300468.SZ", name: "四方精创", relation: 1, theme: "稳定币概念", logic: "A 股无直接加密标的,概念联动", risk: "纯概念", fund: { mcap: "—", val: "—", inv: "—", moat: "—", comp: "恒宝股份等概念股" } },
];

// 主题周期定位与操盘框架
// stage: early(早期信号) / mid(中期主升) / peak(高峰泡沫) / exit(退潮)
export const PLAYBOOK = [
  {
    theme: "存储",
    stage: "peak",
    stageNote: "高峰区间(后段风险大于机会)",
    basis: [
      "价格维度:SNDK 一年最高约 50 倍并纳入纳斯达克100,MU/模组股全线数倍——主升浪的利润最丰厚段已走完",
      "共识维度:『永远缺存储』从孙宇晨的逆向观点(2025-11)变成散户口号(2026)——逆向信号消失即高峰特征",
      "供给维度:HBM 产能售罄至 2027-28 属实,但三星/海力士/美光已大幅上调资本开支,新产能 2026H2-2027 投放,供给反转在路上",
      "结构维度:二线补涨(佰维、江波龙类模组股)与分析师目标价竞赛,是历史上存储周期顶部的典型形态",
      "供给端套现维度(关键增量):SK 海力士(HBM 份额约 60%,年内涨超 300%)拟 7 月 10 日前后以 ADR 登陆纳斯达克(SKHY),发行 1779 万股新股募资约 290 亿美元——史上最大级别。产业链最强玩家选择在此刻卖出天量新股,是教科书级的『聪明钱在顶部派发』信号(可类比 2011-05 嘉能可 IPO 之于大宗商品顶、2021-04 Coinbase 上市之于 BTC 阶段顶)",
    ],
    stages: {
      early: { window: "2024H2-2025Q3(已过)", signals: "NAND/DRAM 合约价见底回升、大厂减产、HBM 订单能见度提升", tickers: "MU、兆易创新(当时的正确入场点)" },
      mid: { window: "2025Q4-2026H1(已走完大半)", signals: "HBM 售罄至 2027-28、SNDK 入 NDX、模组厂利润暴增、涨价扩散到利基存储", tickers: "SNDK、MU、江波龙" },
      peak: { window: "当前 → SKHY 上市窗口", signals: "股价对利好钝化、散户共识化、资本开支大幅上调、二线鸡犬升天;SKHY 上市前的同业映射拉升与上市周的情绪高潮大概率是本轮『最后的烟火』", tickers: "利用上市前后的拉升分批派发,不做买入窗口" },
      exit: { window: "触发即离场", signals: "① SKHY 上市后跌破发行价且 MU/SNDK 走出更低的高点;② NAND/DRAM 合约价环比转跌;③ MU 财报(2026-09 下旬)HBM 指引下修;④ 渠道库存天数回升——任一出现执行下一档减仓,②③同时出现清仓", tickers: "弹性最大的模组/二线先卖,MU 最后" },
    },
    tactics: "【持仓退出方案(三段式,围绕 SKHY 上市事件)】第一段·即刻:上市前的同业拉升中先卖 1/4-1/3,锁定利润(海力士 290 亿美元新股供给 = 产业链最强玩家在顶部套现,事件本身利多情绪、利空筹码);第二段·上市周:若 MU/SNDK/WDC 随 SKHY 挂牌出现放量冲高(blow-off),继续派发至剩 1/3 底仓——上市周是派发窗口不是加仓窗口;第三段·上市后 4-8 周:底仓去留看三个硬指标——SKHY 相对发行价强弱、MU 九月末财报 HBM 指引、TrendForce 合约价月报环比,任一恶化即清底仓。全程铁律:20 周均线跌破无条件减半;抛物线加速日(单日 +8% 以上放量)是卖点不是买点。空仓者:不参与 SKHY 打新式追高;若上市后出现 20-30% 回调且合约价仍环比上行,才有最后一段低吸的赔率。",
  },
  {
    theme: "物理AI",
    stage: "early",
    stageNote: "早期后段:0→1 验证事件密集落地,入局窗口正在打开(但短线已过热)",
    basis: [
      "订单维度(新):优必选 2026-07-01 宣布人形机器人订单破万台并公布售价——从 2025 年全行业千台级到万台级订单,0→1 验证在加速,早期→中期的过渡可能提前到 2026H2-2027H1",
      "量产维度(新):特斯拉弗里蒙特工厂 Model S/X 产线已于 5 月停产改造,Optimus 产线定于 7 月底-8 月投产,初期目标年产能 100 万台——这是本赛道最大的单一验证事件,但媒体已质疑其『承诺多于进展』且马斯克有跳票史",
      "资金维度:TRON AI 基金 2026-05 从 1 亿扩至 10 亿美元,软银/英伟达同期布局——聪明钱进场但收入未兑现,行业普遍亏损、以 PS 估值(优必选 PS 约 25 倍)",
      "温度维度:绿的谐波单日 +17% 级别的波动、A股零部件股 PE 百倍级——题材短线过热,当下不是舒适的建仓点",
      "自利维度:孙宇晨『三年唯一主线』属营销式表述,与其基金存在先建仓后喊单的共振;TRON AI 基金的投资名单是核对『他真买了什么』的清单",
    ],
    stages: {
      early: { window: "当前(2026H2)", signals: "订单从千台级跳到万台级(优必选破万)、Optimus 产线投产、融资密集但收入未确认", tickers: "确定性优先:NVDA(算力/仿真)、三花智控(执行器,主业有 PE 托底)、速腾聚创(感知);过热的绿的谐波类等回调 20%+ 再接" },
      mid: { window: "验证后(可能提前至 2026H2-2027H1)", signals: "Optimus 实际下线并批量交付、行业季度出货环比 +50%、优必选万台订单开始确认收入、零部件公司机器人收入占比 >30%", tickers: "重心从零部件向整机+算力平移:优必选、TSLA、埃斯顿" },
      peak: { window: "渗透率叙事泛滥时", signals: "全行业 PS >40 倍、整机厂扎堆 IPO、券商画 2035 渗透率大饼、零部件估值超主业十倍", tickers: "逐批兑现利润" },
      exit: { window: "订单证伪时", signals: "Optimus 量产连续推迟、万台订单交付/收入确认不及、示范订单退货", tickers: "题材小盘先崩,最后才是 NVDA/TSLA" },
    },
    tactics: "【入局/切换路线图(四步)】Step0·现在:建 2-3% 观察仓,只买有基本面托底的确定性(NVDA/三花智控/速腾聚创);绿的谐波类单日+17%的过热股严禁追,等 20%+ 回调分批接。Step1·硬验证加仓:以下任一落地→加至 5-8%:① Optimus 实际下线并对外交付(不是发布会);② 优必选万台订单开始确认收入(看中报/快报);③ 行业季度出货环比 +50%。Step2·与存储退出联动(资金切换):存储线退出信号(SKHY 上市后走弱/合约价环比转负/MU 指引下修)触发后,把存储兑现资金的 30-50% 滚动切入物理 AI——完成『三缺论 → 物理AI』的仓位轮动,其余留现金。Step3·兑现:全行业 PS>40 倍或整机扎堆 IPO 时逐批了结。铁律:单标的 -20% 硬止损;事件当日暴涨不追(Optimus 投产、机器人大会都是『买预期卖事实』的兑现点);每季核对 TRON AI 基金公告与自己持仓的重合度,防止成为他喊单的接盘方。",
  },
  {
    theme: "能源/核电",
    stage: "mid",
    stageNote: "中期(逻辑持续兑现,波动小于存储/机器人)",
    basis: [
      "需求维度:AI 数据中心长期购电协议(PPA)持续落地,CEG 类公司已有真实合同与利润兑现——不是纯叙事",
      "孙宇晨维度:『长期缺能源』是其三缺论中确定性最高、但弹性最低的一条",
      "A/H 维度:中国核电/中广核电力受电价管制,弹性远低于美股 IPP,属防守型配置",
    ],
    stages: {
      early: { window: "2024(已过)", signals: "首批科技公司核电 PPA 签约", tickers: "CEG、VST(当时)" },
      mid: { window: "当前", signals: "PPA 单价与年限持续改善、SMR 审批推进、电价中枢上移", tickers: "CEG 为主,A/H 核电作红利防守" },
      peak: { window: "警惕", signals: "SMR 概念股(无收入)市值超过在运核电公司、电价见顶", tickers: "回避无收入 SMR 概念(OKLO 类)重仓" },
      exit: { window: "触发再议", signals: "数据中心资本开支下修、PPA 签约停滞", tickers: "—" },
    },
    tactics: "作为组合的压舱石逢回调配置,不追高;跟踪季度 PPA 签约公告与数据中心资本开支指引;美股选有真实合同的 IPP,回避纯 SMR 叙事;A/H 核电按股息率买卖(股息率 <3.5% 时性价比消失)。",
  },
  {
    theme: "加密/稳定币",
    stage: "peak",
    stageNote: "周期后段(2023-09 起算的牛市已运行逾两年)",
    basis: [
      "周期维度:孙宇晨 2023-09『两年内新牛市』已兑现,按其自身周期论,当前处于牛市成熟-后段",
      "事件维度:WLFI 互诉、国会对 SEC 撤案的追查,是孙系资产与特朗普概念的持续黑天鹅源",
      "结构维度:币库股(DAT)板块已现 mNAV 折价,加密股对币价的放大器效应转向双向",
    ],
    stages: {
      early: { window: "2023H2(已过)", signals: "ETF 预期、减半临近", tickers: "COIN、MSTR(当时)" },
      mid: { window: "2024-2025(已过)", signals: "ETF 通过、大选行情、稳定币立法", tickers: "CRCL IPO、HOOD" },
      peak: { window: "当前", signals: "币库股折价、散户杠杆高企、监管红利兑现完毕", tickers: "只留核心仓(CRCL/COIN),投机仓清退" },
      exit: { window: "触发即离场", signals: "BTC 跌破 200 日线且 ETF 连续净流出、稳定币立法出现倒退", tickers: "全线防守" },
    },
    tactics: "此阶段做减法:核心仓只留有真实现金流的 CRCL/COIN 且仓位减半;TRON(股票)只做诉讼节点的事件博弈(和解=利好出尽反弹,恶化=下杀),单笔 ≤1%,预设止损;不碰 DJT 情绪盘;港股 OSL 仅在港政策催化窗口做波段。",
  },
  {
    theme: "TRON直接线",
    stage: "peak",
    stageNote: "高风险投机(与主题周期无关,纯事件与稀释博弈)",
    basis: [
      "稀释维度:10 亿美元 shelf + $0.50 优先股/权证结构悬顶,卖股买币飞轮在 TRX 下跌中变负反馈",
      "监管维度:国会质询上市资格未落地;SEC 和解的政治稳定性存疑",
      "诉讼维度:与 WLFI 互诉进入发现程序,任何爆料都可能双向 20%+ 波动",
    ],
    stages: {
      early: { window: "2025-06(已过)", signals: "借壳公告日 +460-530%", tickers: "事件套利者的窗口" },
      mid: { window: "2025H2(已过)", signals: "财库扩张、派息叙事", tickers: "—" },
      peak: { window: "当前", signals: "增发落地、诉讼消息主导波动", tickers: "仅事件驱动" },
      exit: { window: "任一触发", signals: "纳斯达克问询/退市风险、TRX 单日 -20%、shelf 大额执行", tickers: "无条件离场" },
    },
    tactics: "只做事件、不做持有:诉讼和解公告、财报派息兑现是做多窗口;增发公告、国会听证是做空/回避窗口;仓位 ≤1%,当日设止损,不留隔夜重仓;把它当作孙宇晨营销机器的衍生品而非公司股票。",
  },
];

// 监控信源(RSS)。X 无免费 API:主通道用 Google News 聚合(可捕获媒体转述的 X 言论);
// 设置 X_BEARER_TOKEN secret 后自动启用 X API 直连。
export const SOURCES = [
  // 注意:查询不加 crypto 之类的领域词,避免漏掉他谈存储/物理AI/能源等非加密主题的言论
  { name: "GoogleNews-EN", url: "https://news.google.com/rss/search?q=%22Justin+Sun%22&hl=en-US&gl=US&ceid=US:en" },
  { name: "GoogleNews-ZH", url: "https://news.google.com/rss/search?q=%E5%AD%99%E5%AE%87%E6%99%A8&hl=zh-CN&gl=CN&ceid=CN:zh-Hans" },
  { name: "GoogleNews-TRON", url: "https://news.google.com/rss/search?q=%22Tron+Inc%22+OR+%22TRX+treasury%22&hl=en-US&gl=US&ceid=US:en" },
  { name: "GoogleNews-科技主题", url: "https://news.google.com/rss/search?q=%E5%AD%99%E5%AE%87%E6%99%A8+(%E7%89%A9%E7%90%86AI+OR+%E5%AD%98%E5%82%A8+OR+%E6%9C%BA%E5%99%A8%E4%BA%BA+OR+%E8%83%BD%E6%BA%90)&hl=zh-CN&gl=CN&ceid=CN:zh-Hans" },
  { name: "BingNews", url: "https://www.bing.com/news/search?q=%22Justin+Sun%22+OR+%E5%AD%99%E5%AE%87%E6%99%A8&format=rss" },
  // 存储线退出触发信号专用:SKHY 上市动态 + NAND/DRAM 价格拐点
  { name: "BingNews-存储信号", url: "https://www.bing.com/news/search?q=%22SK+hynix%22+ADR+OR+SKHY+OR+%22NAND+price%22+OR+%22DRAM+price%22&format=rss" },
  { name: "Cointelegraph", url: "https://cointelegraph.com/rss/tag/justin-sun" },
];

// 自动打标规则
export const TAG_RULES = [
  { tag: "预判", re: /predict|forecast|price target|bull|bear|expects?|预测|预判|牛市|熊市|看涨|看跌/i },
  { tag: "诉讼/监管", re: /SEC|lawsuit|sue[ds]?|court|subpoena|congress|诉讼|起诉|监管|国会|和解|反诉/i },
  { tag: "资本动作", re: /invest|acqui|merger|treasury|stake|shelf|dividend|buy|purchase|收购|投资|增持|财库|增发|派息|上市/i },
  { tag: "WLFI/特朗普", re: /WLFI|World Liberty|Trump|特朗普/i },
  { tag: "稳定币", re: /stablecoin|USDT|USDD|Tether|Circle|CRCL|稳定币/i },
  { tag: "营销", re: /dinner|lunch|auction|banana|donat|charity|午餐|晚宴|拍卖|慈善|香蕉/i },
  { tag: "物理AI/机器人", re: /physical\s?AI|embodied|robot|humanoid|drone|optimus|unitree|物理\s?AI|具身|机器人|人形|无人机|空间计算|太空|space/i },
  { tag: "存储/芯片", re: /storage|memory|HBM|NAND|flash|SanDisk|Micron|hynix|semiconductor|chip|存储|闪存|闪迪|芯片|半导体|美光/i },
  { tag: "能源", re: /energy|nuclear|power\s?plant|uranium|电力|能源|核电|铀/i },
];
