import {reviewFocus} from './research-monitor.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderResearch(d,en=false){
 const title=en?'Company disclosure monitor':'公司披露监控';
 const path=en?'/en/research':'/research';
 const ok=(d.issuers??[]).filter(x=>x.status==='ok').length;
 const events=(d.events??[]).slice(0,36);
 const health={ok:en?'Checked':'已检查',partial:en?'Partial coverage':'部分来源待更新',not_ready:en?'Awaiting first check':'等待首次检查'};
 const label=x=>({ok:en?'Available':'可用',error:en?'Failed — retained evidence':'获取失败，保留旧证据',stale:en?'Stale / unverified':'过期或未核实'}[x]??x);
 return `<!doctype html><html lang="${en?'en':'zh-CN'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} · SunWatch</title><meta name="description" content="${en?'Monitor official company releases for twelve AI-related stocks, with source links, observation times and a separate historical SEC archive.':'追踪十二股官方 RSS 与公司公告，显示原文、首次发现时间和来源状态，并保留历史 SEC 申报档案。'}">
<link rel="canonical" href="https://invest.agiscorecard.com${path}"><link rel="alternate" hreflang="zh-CN" href="https://invest.agiscorecard.com/research"><link rel="alternate" hreflang="en" href="https://invest.agiscorecard.com/en/research"><link rel="alternate" hreflang="x-default" href="https://invest.agiscorecard.com/en/research">
<style>:root{--bg:#f6f7f9;--card:#fff;--ink:#1a202c;--muted:#64748b;--line:#e2e8f0;--accent:#2563eb}@media(prefers-color-scheme:dark){:root{--bg:#0f141a;--card:#171e26;--ink:#e6edf3;--muted:#a6b5c8;--line:#2a3441;--accent:#83b4ff}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.65 system-ui,-apple-system,sans-serif}.wrap{max-width:1000px;margin:auto;padding:24px 18px 64px}nav{display:flex;gap:18px;flex-wrap:wrap}a{color:var(--accent)}h1{font-size:clamp(25px,5vw,37px);margin-bottom:10px}h2{font-size:21px}.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px;margin:12px 0}.meta{color:var(--muted);font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.grid .card{margin:0}button{background:var(--accent);color:var(--bg);border:0;border-radius:8px;padding:11px 18px;font:inherit;cursor:pointer}button:disabled{opacity:.55;cursor:wait}.event{border-left:4px solid var(--accent)}.tag{display:inline-block;padding:2px 8px;border:1px solid var(--line);border-radius:5px;font-size:12px;margin-left:6px}time,.url{overflow-wrap:anywhere}.warning{border-left:4px solid #cb8c1b}.stat{font-size:26px;font-weight:700}.links{display:flex;gap:18px;flex-wrap:wrap}#analytics{margin-top:30px;border-top:1px solid var(--line);padding-top:16px}#analytics button{font-size:12px;margin:6px 8px 0 0}</style></head><body><main class="wrap">
<nav><a href="${en?'/en':'/'}">SunWatch</a><a href="https://agiscorecard.com/${en?'':'zh/'}portfolio-tracker">${en?'12-stock returns':'12 股收益对比'}</a><a href="${en?'/en/method':'/method'}">${en?'Method':'研究方法'}</a><a href="${en?'/research':'/en/research'}">${en?'中文':'English'}</a></nav>
<h1>${title}</h1><p>${en?'Official company releases, visible sources, questions to revisit.':'保留原始披露，发现新变化，明确下一步复核。'}</p>
<div class="grid"><div class="card"><div class="meta">${en?'Sources checked successfully':'最近检查成功的来源'}</div><div class="stat">${ok} / 12</div><span>${esc(health[d.health]??health.not_ready)}</span></div><div class="card"><div class="meta">${en?'Legacy opinions awaiting review':'历史观点待复核'}</div><div class="stat">${d.review?.pending??0}</div><span>${en?'No fresh review inferred from a page update.':'页面更新不等于观点已重新核实。'}</span></div><div class="card"><div class="meta">${en?'Check interval':'自动检查间隔'}</div><div class="stat">30 ${en?'min':'分钟'}</div><span>${en?'Original portfolio baseline is unchanged.':'原组合建仓基准保持不变。'}</span></div></div>
<p class="meta">${en?'Last source check':'最近来源检查'}：<time>${esc(d.last_check??(en?'Not yet checked':'尚未检查'))}</time></p>
<button id="refresh">${en?'Check for updates':'检查更新'}</button> <span id="refresh-status" role="status" class="meta"></span>
<div class="card warning"><b>${en?'Evidence scope':'当前证据范围'}</b><p>${en?'Automatic checks use company-owned RSS and investor-relations pages. Coverage is company releases, not all SEC filings. Revenue, guidance and valuation changes remain unassessed. Initial records establish a silent baseline; only new releases enter the owner alert queue.':'自动检查来自公司官方 RSS 与投资者关系公告页，无需 SEC 联系人邮箱。覆盖公司公告，不覆盖全部 SEC 法定申报；正文中的收入、指引与估值变化仍需复核。首次加载只建基线，后续新公告进入站长提醒队列。'}</p><p class="meta">${en?'The existing Telegram bot sends private owner alerts. Delivery status is shown below; paid customer broadcasts are not enabled.':'现有 Telegram 机器人向站长私聊发送提醒，以下显示实际送达状态；尚未向付费客户广播。'}</p></div>
${d.snapshot_only?`<div class="card warning"><b>${en?'Initial historical snapshot — automatic collection is not connected':'初始历史快照 · 自动采集尚未接通'}</b><p>${en?'These 60 filings were verified before deployment. The automatic SEC source still needs operator contact configuration. This is not a live feed.':'以下 60 份申报来自上线前核验。SEC 自动访问仍待配置联系人信息；这不是实时更新。'}</p><p class="meta">${en?'Snapshot observed at':'快照核验时间'}：<time>${esc(d.baseline_as_of)}</time></p></div>`:''}
<p class="meta">Telegram：${d.owner_channel?.delivery_health==='acknowledged'?(en?'Acknowledged':'已收到发送回执'):(en?'Awaiting delivery confirmation':'等待发送确认')} · ${en?'Last acknowledged':'最近回执'}：<time>${esc(d.owner_channel?.last_ack_at??'—')}</time></p>
<h2>${en?'Issuer coverage':'公司覆盖与来源状态'}</h2><div class="grid">${(d.issuers??[]).map(x=>`<div class="card"><b>${esc(x.ticker)}</b> <span class="tag">${esc(label(x.status))}</span><p class="meta">${en?'Latest release date':'最新公告日'}：${esc(x.latest_filing_date??'—')}<br>${en?'Last successful check':'上次检查成功'}：<time>${esc(x.last_success_at??'—')}</time></p><a href="${esc(x.source_url)}" target="_blank" rel="noopener noreferrer">${esc(x.source_name??x.ticker)} ${en?'official source':'官方来源'} ↗</a></div>`).join('')}</div>
<h2>${en?'Evidence timeline':'披露证据时间线'}</h2>
${events.length?events.map(e=>`<article class="card event"><b>${esc(e.ticker)} · ${e.evidence_type==='company_release'?(en?'Company release':'公司公告'):esc(e.form)}</b><span class="tag">${e.baseline?(en?'Historical baseline':'历史基线'):e.historical_backfill?(en?'Historical insertion':'补录历史'):(en?'Needs review':'需要复核')}</span>${e.title?`<h3>${esc(e.title)}</h3>`:''}<p>${esc(reviewFocus(e,en))}</p><p class="meta">${en?'Published':'发布日期'}：${esc(e.filing_date)} · ${en?'Report period':'报告期'}：${esc(e.report_date??'—')}<br>${en?'First observed':'首次发现'}：<time>${esc(e.first_seen_at)}</time><br>${e.evidence_type==='company_release'?(en?'Official company source · original headline language retained':'官方公司来源 · 标题保留原文语言'):(en?'Accession: ':'申报编号：')+esc(e.accession)}</p><div class="links"><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${en?'Read original release':'阅读公告原文'} ↗</a>${e.previous_filing?`<a href="${esc(e.previous_filing)}" target="_blank" rel="noopener noreferrer">${en?'Earlier filing of this type':'同类型较早申报'} ↗</a>`:''}</div></article>`).join(''):`<div class="card">${en?'No verified company release snapshot yet. Check source status; this does not mean there were no announcements.':'尚未成功获取公司公告。请检查来源状态，不能据此认定没有公告。'}</div>`}
<p class="meta">${en?'Sources: official company RSS and IR pages. Publication and observation dates differ. Precise feed timestamps are normalized to UTC; date-only records do not imply a verified release time. SEC EDGAR remains a separate historical archive below.':'来源：公司官方 RSS 与 IR 公告页。发布日期与首次发现时间分别记录。有时区的源时间转换为 UTC；仅有日期的公告不假定精确发布时间。SEC EDGAR 历史档案单列如下。'}</p><p class="links"><a href="/api/research">JSON API</a><a href="https://www.sec.gov/search-filings/edgar-application-programming-interfaces">SEC API ${en?'documentation':'说明'}</a></p>
<details class="card"><summary>${en?'Historical SEC archive — automatic SEC collection remains paused':'历史 SEC 申报档案 · SEC 自动采集仍暂停'} (${d.sec_archive?.events?.length??0})</summary><p class="meta">${en?'Fixed snapshot observed at':'固定快照核验时间'}：${esc(d.sec_archive?.as_of??'—')}</p>${(d.sec_archive?.events??[]).map(e=>`<p><a href="${esc(e.url)}" target="_blank" rel="noopener noreferrer">${esc(e.ticker)} · ${esc(e.form)} · ${esc(e.filing_date)}</a></p>`).join('')}</details>
<div id="analytics"><span class="meta">${en?'Optional analytics: measure public page visits only. No private research or Telegram details are sent.':'可选访问统计：仅记录公开页面访问，不发送私人研究或 Telegram 信息。'}</span><br><button id="ga-yes">${en?'Allow analytics':'允许统计'}</button><button id="ga-no">${en?'Decline / turn off':'拒绝／关闭统计'}</button><span id="ga-state" class="meta" role="status"></span></div>
</main><script>
const en=${en};const button=document.getElementById('refresh');button.onclick=async()=>{button.disabled=true;const out=document.getElementById('refresh-status');out.textContent=en?'Checking…':'检查中…';try{const r=await fetch('/api/research-refresh',{method:'POST'});if(!r.ok)throw Error();const d=await r.json();if(!d.ok)throw Error();sessionStorage.setItem('research-refresh',d.reason);location.reload();}catch{out.textContent=en?'Check failed; existing evidence retained.':'检查失败；保留已有证据。';button.disabled=false;}};
const old=sessionStorage.getItem('research-refresh');if(old){document.getElementById('refresh-status').textContent=old==='rate_limited'?(en?'Showing recent check; source polling is rate limited.':'已显示最近检查结果；来源采集有频率限制。'):(en?'Check completed.':'检查完成。');sessionStorage.removeItem('research-refresh');}
let poll;function schedule(){clearTimeout(poll);if(!document.hidden)poll=setTimeout(async()=>{try{const r=await fetch('/api/research');const d=await r.json();if(d.last_check!==${JSON.stringify(d.last_check??null)}){location.reload();return;}}catch{}schedule();},60000);}document.addEventListener('visibilitychange',schedule);schedule();
const gaKey='sunwatch_analytics_consent_v1',gaId='G-FZXLMBB5QB';let gaStarted=false;
function readChoice(){try{return localStorage.getItem(gaKey)}catch{return null}}
function startGA(){if(gaStarted||location.hostname!=='invest.agiscorecard.com'||navigator.webdriver||navigator.doNotTrack==='1'||navigator.globalPrivacyControl===true||/[?&](?:ci|__ci|qa|__qa)=/.test(location.search))return;gaStarted=true;window['ga-disable-'+gaId]=false;window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag('consent','default',{analytics_storage:'granted',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});gtag('js',new Date());gtag('config',gaId,{send_page_view:false,allow_google_signals:false,allow_ad_personalization_signals:false});gtag('event','page_view',{page_location:location.origin+location.pathname,page_title:document.title,page_referrer:'',site_id:'sunwatch'});const script=document.createElement('script');script.async=true;script.src='https://www.googletagmanager.com/gtag/js?id='+gaId;document.head.append(script);}
function choice(yes){try{localStorage.setItem(gaKey,yes?'yes':'no')}catch{}if(yes)startGA();else{window['ga-disable-'+gaId]=true;if(window.gtag)gtag('consent','update',{analytics_storage:'denied'});}document.getElementById('ga-state').textContent=yes?(en?'Allowed':'已允许'):(en?'Off':'已关闭');}
document.getElementById('ga-yes').onclick=()=>choice(true);document.getElementById('ga-no').onclick=()=>choice(false);if(readChoice()==='yes')choice(true);else if(readChoice()==='no')choice(false);
</script></body></html>`;
}
